---
- name: Gathering heat-config outputs
  command: "find /var/lib/heat-config/deployed -name '*.notify.json'"
  register: heat_deployed_output
  become: true

- debug: var=heat_deployed_output.stdout_lines

- debug: var={{ item }}
  with_items: heat_deployed_output.stdout_lines

- name: Checking for puppet errors
  command: "jq .deploy_status_code {{ item }}"
  register: result
  failed_when: result.std_out != 0
  become: true
  with_items: heat_deployed_output.stdout_lines

- debug: var=result
