---
- name: Gathering heat-config outputs
  find: paths="/var/lib/heat-config/deployed -name '*.notify.json'"
  register: deployed-heat-config
  become: true

- name: Checking for puppet errors
  command: jq .deploy_status_code {{ items }}
  register: result
  failed_when: result.std_out != 0
  with_items: heat-config-outputs

- debug: name=result
