---
- name: Run Glance DB sync
  shell:  glance-manage --config-file=/etc/glance/glance-registry.conf db_sync
  run_once: true
  become: true
  when: "inventory_hostname in groups['glance-api']
        and {{ not update_services | bool }}"
  tags: glance_db_sync
