---
- name: Update glance packages
  yum:
    name: openstack-glance
    state: latest
  when: "inventory_hostname in groups['glance-api']
         or inventory_hostname in groups['glance-registry']"
  become: true
  tags: glance_package_update

- name: Update python glance packages
  yum:
    name:
      - python-glance
      - python-glance-store
    state: latest
  when: "inventory_hostname in groups['glance-api']
         or inventory_hostname in groups['glance-registry']"
  become: true
  tags: glance_package_update
